export  enum RouterNames {
    ROOM = "ROOM_VIEW",
    SETUP = "SETUP_VIEW",
    PLAY_GROUND = "PLAY_GROUND",
    PLAY_GROUND_USERS = "PLAY_GROUND_USERS",
    PLAY_GROUND_DIALOG = "PLAY_GROUND_DIALOG",
  }