export enum WS_MSG_TYPE {
    ENTER_ROOM = "ENTER_ROOM",
    ENTER_ROOM_FINISHED = "ENTER_ROOM_FINISHED",
    GET_ROOM_INFO = "ROOM_INFORMATION",
    UPDATE_USER_ACCOUNT_SERV = "UPDATE_USER_ACCOUNT_SERV",
    UPDATE_USER_ACCOUNT_CLI = "UPDATE_USER_ACCOUNT_CLI",
    SEND_ROOM_INFO = "SEND_ROOM_INFORMATION"
}
