export enum WS_MSG_TYPE {
    ENTER_ROOM = "ENTER_ROOM",
    ENTER_ROOM_FINISHED = "ENTER_ROOM_FINISHED",
    GET_ROOM_INFO = "ROOM_INFORMATION",
    UPDATE_USER_ACCOUNT_SERV = "UPDATE_USER_ACCOUNT_SERV",
    UPDATE_USER_ACCOUNT_CLI = "UPDATE_USER_ACCOUNT_CLI",
    SEND_ROOM_INFO = "SEND_ROOM_INFORMATION",
    LOG_OUT= "LOG_OUT",
    SEND_INSTRUCTION_SERV = "SEND_INSTRUCTION_SERV",
    SEND_INSTRUCTION_CLI = "SEND_INSTRUCTION_CLI",
    UPDATE_RECORD_MODE_SERV = "UPDATE_RECORD_MODE_SERV",
    UPDATE_RECORD_MODE_CLI = "UPDATE_RECORD_MODE_CLI",
}
